### ISSUE TITLE
Standard URL

### ISSUE THREAD

**Issue by javiavid** [felipetappata/obsidian-link-preview#1]
I just saw your plugin and I think it's a great idea, there are many times that you copy links from websites and then you don't really remember what it was.

I'm trying it with a standard text url but it doesn't work. Does it have to be in a specific format?

![image](https://github.com/user-attachments/assets/186ed08b-065b-4b49-877f-4da988cdfb21)

**Comment by felipetappata** [comment]
Hi @javiavid, thanks for opening the issue. I think the issue may be that you are in editing mode, for which the plugin does not enable the hover pane. Try entering preview mode and seeing if the issue persists.
